# Generated by Django 3.2.4 on 2021-08-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_avatar_filenumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='filenumb',
            field=models.PositiveIntegerField(default=196),
        ),
    ]
