# Generated by Django 3.2.4 on 2021-09-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_avatar_filenumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='filenumb',
            field=models.PositiveIntegerField(default=553),
        ),
    ]
