# Generated by Django 3.2.4 on 2021-08-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessicon',
            name='icon',
            field=models.ImageField(upload_to='business_icons/'),
        ),
    ]
