# Generated by Django 3.2.4 on 2021-08-15 02:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_businessicon_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessicon',
            old_name='business',
            new_name='business_clasification',
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(max_length=1024, verbose_name='Address line 2')),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP / Postal code')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('country', models.CharField(max_length=3, verbose_name='Country')),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank='True', null=True)),
                ('image1', models.ImageField(null=True, upload_to='business_images/')),
                ('image2', models.ImageField(null=True, upload_to='business_images/')),
                ('image3', models.ImageField(null=True, upload_to='business_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.businessclasification')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sites.businessicon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_business', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
